/*
	Tên : Đinh Minh Đức
	MSSV : 25520323
*/

--BUOI THUC HANH 1 :

--I. CSDL QUAN LY BAN HANG : 

-- CAU 1 : 

CREATE DATABASE QuanLyBanHang;

USE QuanLyBanHang;

CREATE TABLE KHACHHANG
(
	MAKH char(4) PRIMARY KEY, 
	HOTEN varchar(40),
	DIACHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	NGDK smalldatetime,
	DOANHSO money
)

CREATE TABLE NHANVIEN
(
	MANV char(4) PRIMARY KEY, 
	HOTEN varchar(20),
	SODT varchar(20),
	NGVL smalldatetime
)

CREATE TABLE SANPHAM
( 
	MASP char(4) PRIMARY KEY, 
	TENSP varchar(20),
	DVT varchar(20),
	NUOCSX varchar(40),
	GIA money
)

CREATE TABLE HOADON
( 
	SOHD int PRIMARY KEY,
	NGHD smalldatetime, 
	MAKH char(4),
	MANV char(4),
	TRIGIA money	
)

ALTER TABLE 
	HOADON
ADD CONSTRAINT 
	FK_HOADON_KH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE 
	HOADON
ADD CONSTRAINT 
	FK_HOADON_NV
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

CREATE TABLE CTHD 
( 
	SOHD int, 
	MASP char(4)
)

ALTER TABLE 
	CTHD
ADD 
	SL int;

ALTER TABLE 
	CTHD
ADD CONSTRAINT 
	FK_CTHD_SP
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);

ALTER TABLE 
	CTHD
ADD CONSTRAINT 
	FK_HOADON_SOHD
FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD);

--CAU 2 : 
ALTER TABLE 
	SANPHAM 
ADD 
	GHICHU varchar(20);

--CAU 3 : 
ALTER TABLE 
	KHACHHANG
ADD 
	LOAIKH tinyint;

--CAU 4 : 
ALTER TABLE 
	SANPHAM 
ALTER COLUMN 
	GHICHU varchar(100);

--CAU 5 :
ALTER TABLE 
	SANPHAM 
DROP COLUMN
	GHICHU;

--CAU 6 : 
ALTER TABLE 
	KHACHHANG
ALTER COLUMN
	LOAIKH varchar(20);

--CAU 7 :
ALTER TABLE 
	SANPHAM 
ADD CONSTRAINT
	CK_DVT
CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

--CAU 8 : 
ALTER TABLE 
	SANPHAM 
ADD CONSTRAINT 
	CK_GIA
	CHECK(GIA >= 500) ;

--CAU 9 : 
ALTER TABLE 
	HOADON
ADD CONSTRAINT 
	CK_TRIGIA
	CHECK(TRIGIA >= 500) ;

ALTER TABLE 
	CTHD 
ADD CONSTRAINT
	CK_SL
	CHECK(SL > 0);

--CAU 10 : 
ALTER TABLE 
	KHACHHANG
ADD CONSTRAINT 
	CK_NGSINH_NGDK
	CHECK (NGDK > NGSINH);

--II. CSDL QUAN LY GIAO VU
CREATE DATABASE QuanLyGiaoVu;

USE QuanLyGiaoVu;

CREATE TABLE KHOA
(
	MAKHOA varchar(4) PRIMARY KEY, 
	TENKHOA	varchar(40) NOT NULL, 
	NGTLAP smalldatetime NOT NULL,
	TRGKHOA char(4)
)

CREATE TABLE MONHOC 
(
	MAMH varchar(10) PRIMARY KEY, 
	TENMH varchar(40) NOT NULL, 
	TCTL tinyint, 
	TCTH tinyint, 
	MAKHOA varchar(4),

	FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10), 
	MAMH_TRUOC varchar(10),

	PRIMARY KEY(MAMH, MAMH_TRUOC), 

	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH), 
	FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)
)

CREATE TABLE GIAOVIEN
(
	MAGV char(4) PRIMARY KEY, 
	HOTEN varchar(40) NOT NULL, 
	HOCVI varchar(10),
	HOCHAM varchar(10), 
	GIOITINH varchar(3), 
	NGSINH smalldatetime,
	NGVL smalldatetime, 
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4),

	FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE LOP 
(
	MALOP char(3) PRIMARY KEY, 
	TENLOP varchar(40), 
	TRGLOP char(5), 
	SISO tinyint, 
	MAGVCN char(4), 

	FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
)

CREATE TABLE HOCVIEN
(
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40), 
	MALOP char(3), 

	FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)

ALTER TABLE 
	LOP
ADD CONSTRAINT 
	FK_TRGLOP
	FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);

CREATE TABLE GIANGDAY
(
	MALOP char(3), 
	MAMH varchar(10),
	MAGV char(4), 
	HOCKY tinyint, 
	NAM smallint, 
	TUNGAY smalldatetime, 
	DENNGAY smalldatetime, 

	PRIMARY KEY (MALOP, MAMH), 

	FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV), 
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)

CREATE TABLE KETQUATHI 
(
	MAHV char(5), 
	MAMH varchar(10), 
	LANTHI tinyint NOT NULL,
	NGTHI smalldatetime, 
	DIEM numeric(4,2), 
	KQUA varchar(10), 

	PRIMARY KEY (MAHV, MAMH, LANTHI),

	FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV), 
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH), 
)

ALTER TABLE 
	HOCVIEN
ADD 
	GHICHU varchar(40), 
	DIEMTB numeric(4,2),
	XEPLOAI varchar(10);

-- CAU 3 : 
ALTER TABLE 
	GIAOVIEN 
ADD CONSTRAINT 
	CK_GIOITINH
	CHECK(GIOITINH IN ('Nam', 'Nu'));

ALTER TABLE 
	HOCVIEN
ADD CONSTRAINT
	HV_CK_GIOITINH
	CHECK(GIOITINH IN ('Nam', 'Nu'));

-- CAU 4 :
ALTER TABLE 
	KETQUATHI
ADD CONSTRAINT 
	CK_DIEM
	CHECK(DIEM <= 10 AND DIEM >=0)

-- CAU 5 : 
ALTER TABLE 
	KETQUATHI
DROP COLUMN 
	KQUA;

ALTER TABLE 
	KETQUATHI
ADD KQUA AS 
	CASE 
		WHEN DIEM >= 5 THEN 'Dat'
		ELSE 'Khong dat'
	END;

-- CAU 6 :
ALTER TABLE 
	KETQUATHI
ADD CONSTRAINT 
	CK_LANTHI
	CHECK(LANTHI <= 3 AND LANTHI >=0);

-- CAU 7 :
ALTER TABLE
	GIANGDAY
ADD CONSTRAINT 
	CK_HOCKY
	CHECK(HOCKY IN (1, 2, 3));

-- CAU 8 : 
ALTER TABLE 
	GIAOVIEN 
ADD CONSTRAINT
	CK_HOCVI
	CHECK(HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));

